using System;
using System.Collections.Generic;
using System.Linq;

namespace ArcaneLegends.Data
{
    /// <summary>
    /// The skilling/crafting economy tables, deserialised from StreamingAssets/economy.json
    /// (generated by tools/export-unity-data.mjs from public/items.js and public/lessons.js).
    ///
    /// GENERATED, NEVER HAND-EDITED. These are ~60 tuned rows whose transcription errors are
    /// invisible: a wrong `xp` or a wrong `req` reads as a balance decision, not as a bug. Same
    /// reasoning as the card data — see docs/MISTAKES.md A6.
    ///
    /// Two things arrive here already flattened, because they are CODE in the JS source:
    ///   - equipment stats, which `equipmentFor(metal, slot)` computes from the metal's tier. All
    ///     25 rows are exported pre-computed so C# cannot re-derive the formula differently.
    ///   - home upgrade cost/timber, which are `cost(n)`/`timber(n)` functions. Exported as a
    ///     per-level table.
    /// </summary>
    [Serializable]
    public class EconomyData
    {
        public List<SkillDef> skills = new();
        public List<MaterialDef> materials = new();
        public List<BarDef> bars = new();
        public List<PotionDef> potions = new();
        public List<MetalDef> metals = new();
        public List<SlotDef> slots = new();
        public List<EquipmentDef> equipment = new();
        public List<CardMaterialDef> cardMaterials = new();
        public List<EnchantDef> enchants = new();
        public List<HomeUpgradeDef> homeUpgrades = new();

        /// <summary>material id -> gather cooldown in ms. Source formula: 8000 + lvl*500.</summary>
        public Dictionary<string, int> gatherRegenMs = new();

        public PristineDef pristine = new();

        /// <summary>Skill XP multiplier per Tavern level (0.10 = +10% each).</summary>
        public double tavernSkillXpPerLevel = 0.10;

        /// <summary>Which lessons teach which technique. Mastery is DERIVED from these + the
        /// player's completed list on every read — never stored.</summary>
        public List<LessonTeachDef> lessonTeaches = new();
        public List<TechniqueDef> techniques = new();

        // ---------------------------------------------------------------- lookups

        private Dictionary<string, MaterialDef> _materialById;
        private Dictionary<string, BarDef> _barById;
        private Dictionary<string, PotionDef> _potionById;
        private Dictionary<string, EquipmentDef> _equipmentById;
        private Dictionary<string, EnchantDef> _enchantById;
        private Dictionary<string, CardMaterialDef> _cardMaterialById;
        private Dictionary<string, HomeUpgradeDef> _homeUpgradeById;
        private Dictionary<string, LessonTeachDef> _lessonById;

        /// <summary>Build the id indexes. Call once after deserialising, before any lookup.</summary>
        public void BuildIndexes()
        {
            _materialById     = materials.ToDictionary(m => m.id);
            _barById          = bars.ToDictionary(b => b.id);
            _potionById       = potions.ToDictionary(p => p.id);
            _equipmentById    = equipment.ToDictionary(e => e.id);
            _enchantById      = enchants.ToDictionary(e => e.id);
            _cardMaterialById = cardMaterials.ToDictionary(m => m.id);
            _homeUpgradeById  = homeUpgrades.ToDictionary(u => u.id);
            _lessonById       = lessonTeaches.ToDictionary(l => l.id);
        }

        private static T Get<T>(Dictionary<string, T> map, string id) where T : class =>
            id != null && map != null && map.TryGetValue(id, out var v) ? v : null;

        public MaterialDef Material(string id) => Get(_materialById, id);
        public BarDef Bar(string id) => Get(_barById, id);
        public PotionDef Potion(string id) => Get(_potionById, id);
        public EnchantDef Enchant(string id) => Get(_enchantById, id);
        public CardMaterialDef CardMaterial(string id) => Get(_cardMaterialById, id);
        public HomeUpgradeDef HomeUpgrade(string id) => Get(_homeUpgradeById, id);
        public LessonTeachDef Lesson(string id) => Get(_lessonById, id);

        public EquipmentDef Equipment(string id) => Get(_equipmentById, id);
        /// <summary>The one equipment row for a metal×slot pair. Ids are "{metal}_{slot}".</summary>
        public EquipmentDef Equipment(string metal, string slot) => Equipment($"{metal}_{slot}");

        public int RegenMsFor(string materialId) =>
            gatherRegenMs.TryGetValue(materialId, out var ms) ? ms : 0;

        // ---------------------------------------------------------------- pristine ids
        // A pristine find is a SELL-ONLY variant derived from a real material, not a row in any
        // table. Keeping the id arithmetic here means only the sell path ever has to know pristine
        // ids exist — every recipe table stays untouched. Mirrors items.js's own reasoning.

        public string PristineIdFor(string materialId) => pristine.prefix + materialId;

        public bool IsPristineId(string itemId) =>
            itemId != null && itemId.StartsWith(pristine.prefix, StringComparison.Ordinal);

        public string BaseMaterialIdFor(string itemId) =>
            IsPristineId(itemId) ? itemId.Substring(pristine.prefix.Length) : itemId;

        /// <summary>Gold one unit of an item sells for; 0 if it is not sellable.</summary>
        public int SellValueOf(string itemId)
        {
            if (IsPristineId(itemId))
            {
                var baseMat = Material(BaseMaterialIdFor(itemId));
                return baseMat == null ? 0 : baseMat.value * pristine.sellMultiplier;
            }
            var m = Material(itemId);
            if (m != null) return m.value;
            var b = Bar(itemId);
            if (b != null) return b.value;
            var p = Potion(itemId);
            return p?.value ?? 0;
        }

        /// <summary>Display name for any sellable item id, pristine variants included.</summary>
        public string DisplayName(string itemId)
        {
            if (IsPristineId(itemId))
            {
                var baseMat = Material(BaseMaterialIdFor(itemId));
                return baseMat == null ? itemId : "Pristine " + baseMat.name;
            }
            return Material(itemId)?.name ?? Bar(itemId)?.name ?? Potion(itemId)?.name
                   ?? CardMaterial(itemId)?.name ?? itemId;
        }

        // ---------------------------------------------------------------- validation

        /// <summary>
        /// Problems with the economy tables themselves — same contract as GameData.Validate():
        /// a list of human-readable strings, empty when clean. Catches an export that dropped rows
        /// or a recipe that points at an item id nothing produces.
        /// </summary>
        public List<string> Validate()
        {
            var problems = new List<string>();
            if (_materialById == null) { problems.Add("BuildIndexes() was never called"); return problems; }

            if (materials.Count == 0) problems.Add("no materials");
            if (bars.Count == 0) problems.Add("no bars");
            if (equipment.Count == 0) problems.Add("no equipment");

            var skillIds = new HashSet<string>(skills.Select(s => s.id));
            foreach (var m in materials)
            {
                if (!skillIds.Contains(m.skill)) problems.Add($"material {m.id}: unknown skill \"{m.skill}\"");
                if (!gatherRegenMs.ContainsKey(m.id)) problems.Add($"material {m.id}: no gather cooldown");
            }

            // Every recipe input must be something the game can actually produce.
            var producible = new HashSet<string>(materials.Select(m => m.id));
            producible.UnionWith(bars.Select(b => b.id));
            producible.UnionWith(cardMaterials.Select(c => c.id));

            void CheckReq(string owner, Dictionary<string, int> req)
            {
                if (req == null) return;
                foreach (var kv in req)
                {
                    if (!producible.Contains(kv.Key)) problems.Add($"{owner}: requires unproducible \"{kv.Key}\"");
                    if (kv.Value <= 0) problems.Add($"{owner}: non-positive quantity for \"{kv.Key}\"");
                }
            }

            foreach (var b in bars) CheckReq($"bar {b.id}", b.req);
            foreach (var p in potions) CheckReq($"potion {p.id}", p.req);
            foreach (var e in enchants) CheckReq($"enchant {e.id}", e.req);

            var barIds = new HashSet<string>(bars.Select(b => b.id));
            foreach (var e in equipment)
                if (!barIds.Contains(e.barId)) problems.Add($"equipment {e.id}: unknown bar \"{e.barId}\"");

            foreach (var cm in cardMaterials)
                foreach (var src in cm.from)
                    if (Material(src) == null) problems.Add($"cardMaterial {cm.id}: unknown source \"{src}\"");

            var techniqueIds = new HashSet<string>(techniques.Select(t => t.id));
            foreach (var l in lessonTeaches)
                foreach (var kv in l.teaches)
                    if (!techniqueIds.Contains(kv.Key)) problems.Add($"lesson {l.id}: unknown technique \"{kv.Key}\"");

            return problems;
        }
    }

    [Serializable] public class SkillDef { public string id, name, icon; }

    [Serializable]
    public class MaterialDef
    {
        public string id, name, icon, skill;
        /// <summary>Skill level required to gather it.</summary>
        public int lvl;
        public int xp, value;
    }

    [Serializable]
    public class BarDef
    {
        public string id, name, icon, metal;
        public int lvl, xp, value;
        public Dictionary<string, int> req = new();
    }

    [Serializable]
    public class PotionDef
    {
        public string id, name, icon;
        public int lvl, xp, value;
        public Dictionary<string, int> req = new();
        /// <summary>HP restored, 0 for a buff potion.</summary>
        public int heal;
        /// <summary>Duel-long stat buffs; both 0 for a healing potion.</summary>
        public int atkBonus, defBonus;
        public bool IsBuff => heal == 0 && (atkBonus != 0 || defBonus != 0);
    }

    [Serializable] public class MetalDef { public string id, name, color; public int tier; }
    [Serializable] public class SlotDef { public string id, name, icon; }

    /// <summary>
    /// One metal×slot item. Stats arrive pre-computed from the exporter — do NOT re-derive them
    /// from `tier` here, or the two formulas can drift apart silently.
    /// </summary>
    [Serializable]
    public class EquipmentDef
    {
        public string id, name, slot, metal, barId, icon, color;
        public int tier, lvl, bars, value;
        public int atk, def, hp, pip, gold;
    }

    [Serializable]
    public class CardMaterialDef
    {
        public string id, name, icon;
        /// <summary>Raw material ids that can be refined into it.</summary>
        public List<string> from = new();
        public int xp, value;
    }

    [Serializable]
    public class EnchantDef
    {
        public string id, name;
        /// <summary>"atk" | "def" | "hp" — which stat `n` is added to.</summary>
        public string stat;
        public int n, lvl, xp, cost;
        public Dictionary<string, int> req = new();
    }

    [Serializable]
    public class HomeUpgradeDef
    {
        public string id, name, icon, desc;
        public int max;
        public List<HomeUpgradeLevel> levels = new();

        /// <summary>Cost to go from level <paramref name="current"/> to the next, or null at max.</summary>
        public HomeUpgradeLevel NextFrom(int current) => levels.FirstOrDefault(l => l.from == current);
    }

    [Serializable] public class HomeUpgradeLevel { public int from, cost, timber; }

    [Serializable]
    public class PristineDef
    {
        /// <summary>Flat percent chance per gather. Deliberately not skill-scaled.</summary>
        public int chancePercent = 6;
        public int sellMultiplier = 5;
        public string prefix = "pristine_";
    }

    [Serializable]
    public class LessonTeachDef
    {
        public string id;
        public int year;
        /// <summary>technique id -> amount taught.</summary>
        public Dictionary<string, int> teaches = new();
    }

    [Serializable] public class TechniqueDef { public string id, name, unit, desc; }
}
