using System;
using System.Collections.Generic;
using System.Linq;

namespace ArcaneLegends.Data
{
    /// <summary>
    /// The game's design data, deserialised from StreamingAssets/gamedata.json.
    ///
    /// That JSON is GENERATED by tools/export-unity-data.mjs from the web build's own modules —
    /// never hand-edited. Retyping 47 cards into C# would introduce transcription errors that no
    /// compiler catches (a wrong atk reads as a balance decision, not a bug), so the data is
    /// faithful by construction and re-exportable if the source changes.
    ///
    /// Deliberately free of any UnityEngine dependency: this and the whole Duel namespace are
    /// plain C#, so the rules can be unit-tested without opening the Editor. That mirrors how the
    /// web build kept its pure modules headlessly testable (644 engine checks) while only the
    /// rendering layer needed a browser — and it is what lets the existing test suite be ported
    /// as a specification rather than rewritten from scratch.
    /// </summary>
    [Serializable]
    public class GameData
    {
        public string generated;
        public int ultChargeMax = 5;
        public List<School> schools = new();
        public List<Rarity> rarities = new();
        public List<SchoolMatchup> schoolBonus = new();
        public List<Card> cards = new();
        public List<CreatureTrait> creatureTraits = new();
        public List<Affinity> affinities = new();
        public List<Ultimate> ultimates = new();

        // Lookups built once after load. Kept private with accessor methods so callers cannot
        // mutate the shared catalog by accident.
        private Dictionary<string, Card> _cardById;
        private Dictionary<string, CreatureTrait> _traitById;
        private Dictionary<string, Ultimate> _ultBySchool;
        private Dictionary<string, Affinity> _affinityBySchool;
        private HashSet<string> _beats;

        /// <summary>Build the lookup tables. Call once after deserialising.</summary>
        public void Index()
        {
            _cardById = cards.ToDictionary(c => c.id);
            _traitById = creatureTraits.ToDictionary(t => t.id);
            _ultBySchool = ultimates.ToDictionary(u => u.school);
            _affinityBySchool = affinities.ToDictionary(a => a.school);
            _beats = new HashSet<string>(schoolBonus.Select(m => m.attacker + ">" + m.defender));
        }

        public Card CardById(string id) =>
            _cardById != null && _cardById.TryGetValue(id, out var c) ? c : null;

        public CreatureTrait TraitById(string id) =>
            id != null && _traitById != null && _traitById.TryGetValue(id, out var t) ? t : null;

        public Ultimate UltimateFor(string school) =>
            school != null && _ultBySchool != null && _ultBySchool.TryGetValue(school, out var u) ? u : null;

        /// <summary>
        /// The elemental ring: fire &gt; ice &gt; storm &gt; myth &gt; life &gt; death &gt; fire.
        /// Non-transitive on purpose — balance sits outside it and neither gives nor takes a bonus.
        /// </summary>
        public bool SchoolBeats(string attacker, string defender) =>
            _beats != null && _beats.Contains(attacker + ">" + defender);

        /// <summary>
        /// The bonus effect a caster's own school adds to a spell of that same school, or null.
        /// Mirrors schoolmagic.js affinityFx(): the caster's school must MATCH the spell's school.
        /// </summary>
        public Effect AffinityFor(string casterSchool, string spellSchool)
        {
            if (string.IsNullOrEmpty(casterSchool) || casterSchool != spellSchool) return null;
            return _affinityBySchool != null && _affinityBySchool.TryGetValue(casterSchool, out var a)
                ? a.effect : null;
        }

        /// <summary>Whether banked charge allows this school's once-per-duel finisher right now.</summary>
        public bool CanUseUltimate(int charge, string school, bool alreadyUsed) =>
            !alreadyUsed && charge >= ultChargeMax && UltimateFor(school) != null;

        /// <summary>
        /// Structural checks, in the spirit of the web build's validateX() functions: every module
        /// there exposes one and the test suite asserts it returns no problems. Returning a list
        /// (rather than throwing or logging) keeps it usable from both tests and an editor tool.
        /// </summary>
        public List<string> Validate()
        {
            var problems = new List<string>();
            if (cards.Count == 0) problems.Add("no cards loaded");

            var ids = new HashSet<string>();
            foreach (var c in cards)
            {
                if (!ids.Add(c.id)) problems.Add($"duplicate card id \"{c.id}\"");
                if (string.IsNullOrEmpty(c.school)) problems.Add($"{c.id}: no school");
                else if (!schools.Any(s => s.id == c.school)) problems.Add($"{c.id}: unknown school \"{c.school}\"");
                if (!rarities.Any(r => r.id == c.rarity)) problems.Add($"{c.id}: unknown rarity \"{c.rarity}\"");
                if (c.type == "creature" && c.hp <= 0) problems.Add($"{c.id}: creature with no hp");
                if (c.type == "spell" && c.effects.Count == 0) problems.Add($"{c.id}: spell with no effects");
                if (c.cost < 0) problems.Add($"{c.id}: negative cost");
            }

            foreach (var s in schools)
            {
                if (UltimateFor(s.id) == null) problems.Add($"{s.id}: no ultimate defined");
                if (!affinities.Any(a => a.school == s.id)) problems.Add($"{s.id}: no affinity defined");
            }

            // Every school except balance must appear exactly once on each side of the ring, or
            // the matchup wheel is lopsided and some school silently has no counter.
            foreach (var s in schools.Where(s => s.id != "balance"))
            {
                if (schoolBonus.Count(m => m.attacker == s.id) != 1)
                    problems.Add($"{s.id}: should beat exactly one school");
                if (schoolBonus.Count(m => m.defender == s.id) != 1)
                    problems.Add($"{s.id}: should be beaten by exactly one school");
            }
            return problems;
        }
    }

    [Serializable] public class School  { public string id; public string name; public string color; }
    [Serializable] public class Rarity  { public string id; public string name; public string color; public int baseValue; }
    [Serializable] public class SchoolMatchup { public string attacker; public string defender; }
    [Serializable] public class Affinity { public string school; public Effect effect; public string why; }

    [Serializable]
    public class Ultimate
    {
        public string school, name, icon, text;
        public List<Effect> effects = new();
    }

    /// <summary>
    /// One effect, in the {k,n} shape every card, ultimate and affinity in this game already
    /// speaks. DuelEngine.ApplyEffects dispatches on <c>k</c>. Keeping one shape for all three
    /// sources is why an ultimate can reuse card effects with no special-casing.
    /// </summary>
    [Serializable]
    public class Effect
    {
        public string k;
        public int n;
        public Effect() { }
        public Effect(string kind, int amount) { k = kind; n = amount; }
    }

    [Serializable]
    public class Card
    {
        public string id, name, school, type, rarity, text, art;
        public int cost, atk, hp;
        /// <summary>Keyword traits printed on the card: haste, taunt, drain, multiAttack.</summary>
        public List<string> keywords = new();
        /// <summary>Numeric effects resolved when the card is played.</summary>
        public List<Effect> effects = new();
        /// <summary>True when the card asks the caster to choose a target.</summary>
        public bool targeted;

        public bool IsCreature => type == "creature";
        public bool IsSpell => type == "spell";
        public bool Has(string keyword) => keywords.Contains(keyword);
    }

    /// <summary>
    /// Per-creature passive/active rules, keyed by creature archetype (see creatures.js RULES).
    /// A fixed schema rather than a loose dictionary so C# gets compile-time field access; the
    /// exporter flattens every known trait, and export-unity-data.mjs must be updated if a new
    /// trait is added to the source table.
    /// </summary>
    [Serializable]
    public class CreatureTrait
    {
        public string id;
        public bool haste, taunt, drain, evade, spellImmune, survive, warband, onPlayFreeze;
        public int regen, thorns, poison, shield, healOnHit, wizardDmg, rageAtk;
        public int onPlayDmgAll, onPlayHealAll, onPlayBuffAll, onPlayBolt, onPlayStealAtk, onPlayDraw;
        public int onAttackDmgAll, onAttackDebuff;
    }
}
